included:
  - unicodoc

excluded:
  - unicodoc.xcodeproj
  - unicodoc/Models/UnicodeBlocks.swift
  - unicodoc/Models/UnicodeBlocks+Japanese.swift

disabled_rules:
  - trailing_comma
  - line_length
  - file_length
  - function_body_length
  - type_body_length
  - identifier_name
  - type_name
  - cyclomatic_complexity
  - function_parameter_count
