import Foundation

extension UnicodeBlocks {
    /// English block name → Japanese translation. Missing entries fall back
    /// to the English name via `UnicodeBlock.localizedName`.
    static let japaneseNames: [String: String] = [
        // Latin & IPA
        "Basic Latin": "基本ラテン文字",
        "Latin-1 Supplement": "ラテン1補助",
        "Latin Extended-A": "ラテン文字拡張A",
        "Latin Extended-B": "ラテン文字拡張B",
        "Latin Extended-C": "ラテン文字拡張C",
        "Latin Extended-D": "ラテン文字拡張D",
        "Latin Extended-E": "ラテン文字拡張E",
        "Latin Extended-F": "ラテン文字拡張F",
        "Latin Extended-G": "ラテン文字拡張G",
        "Latin Extended Additional": "ラテン文字拡張追加",
        "IPA Extensions": "IPA拡張",
        "Phonetic Extensions": "音声記号拡張",
        "Phonetic Extensions Supplement": "音声記号拡張補助",
        "Spacing Modifier Letters": "前進を伴う修飾文字",
        "Modifier Tone Letters": "声調修飾文字",

        // Combining marks
        "Combining Diacritical Marks": "ダイアクリティカルマーク",
        "Combining Diacritical Marks Extended": "ダイアクリティカルマーク拡張",
        "Combining Diacritical Marks Supplement": "ダイアクリティカルマーク補助",
        "Combining Diacritical Marks for Symbols": "記号用ダイアクリティカルマーク",
        "Combining Half Marks": "半記号",

        // Greek / Cyrillic / Armenian / Hebrew
        "Greek and Coptic": "ギリシャ文字およびコプト文字",
        "Greek Extended": "ギリシャ文字拡張",
        "Coptic": "コプト文字",
        "Coptic Epact Numbers": "コプト・エパクト数字",
        "Cyrillic": "キリル文字",
        "Cyrillic Supplement": "キリル文字補助",
        "Cyrillic Extended-A": "キリル文字拡張A",
        "Cyrillic Extended-B": "キリル文字拡張B",
        "Cyrillic Extended-C": "キリル文字拡張C",
        "Cyrillic Extended-D": "キリル文字拡張D",
        "Armenian": "アルメニア文字",
        "Hebrew": "ヘブライ文字",

        // Arabic family
        "Arabic": "アラビア文字",
        "Arabic Supplement": "アラビア文字補助",
        "Arabic Extended-A": "アラビア文字拡張A",
        "Arabic Extended-B": "アラビア文字拡張B",
        "Arabic Extended-C": "アラビア文字拡張C",
        "Arabic Presentation Forms-A": "アラビア表示形A",
        "Arabic Presentation Forms-B": "アラビア表示形B",
        "Arabic Mathematical Alphabetic Symbols": "アラビア数学用英数字記号",
        "Syriac": "シリア文字",
        "Syriac Supplement": "シリア文字補助",
        "Thaana": "ターナ文字",
        "NKo": "ンコ文字",
        "Samaritan": "サマリア文字",
        "Mandaic": "マンダ文字",

        // Indic
        "Devanagari": "デーヴァナーガリー文字",
        "Devanagari Extended": "デーヴァナーガリー文字拡張",
        "Devanagari Extended-A": "デーヴァナーガリー文字拡張A",
        "Bengali": "ベンガル文字",
        "Gurmukhi": "グルムキー文字",
        "Gujarati": "グジャラーティー文字",
        "Oriya": "オリヤー文字",
        "Tamil": "タミル文字",
        "Tamil Supplement": "タミル文字補助",
        "Telugu": "テルグ文字",
        "Kannada": "カンナダ文字",
        "Malayalam": "マラヤーラム文字",
        "Sinhala": "シンハラ文字",
        "Sinhala Archaic Numbers": "シンハラ古数字",
        "Vedic Extensions": "ヴェーダ拡張",

        // Southeast Asia
        "Thai": "タイ文字",
        "Lao": "ラオ文字",
        "Tibetan": "チベット文字",
        "Myanmar": "ミャンマー文字",
        "Myanmar Extended-A": "ミャンマー文字拡張A",
        "Myanmar Extended-B": "ミャンマー文字拡張B",
        "Khmer": "クメール文字",
        "Khmer Symbols": "クメール記号",
        "Tai Le": "タイ・ロ文字",
        "New Tai Lue": "新タイ・ロ文字",
        "Tai Tham": "タイ・タム文字",
        "Tai Viet": "タイ・ヴェト文字",
        "Cham": "チャム文字",
        "Balinese": "バリ文字",
        "Sundanese": "スンダ文字",
        "Sundanese Supplement": "スンダ文字補助",
        "Batak": "バタク文字",
        "Lepcha": "レプチャ文字",
        "Buginese": "ブギス文字",
        "Javanese": "ジャワ文字",
        "Kayah Li": "カヤー・リー文字",
        "Rejang": "レジャン文字",

        // Georgian / Korean / Ethiopic / Cherokee / Canadian / Ogham / Runic
        "Georgian": "ジョージア文字",
        "Georgian Supplement": "ジョージア文字補助",
        "Georgian Extended": "ジョージア文字拡張",
        "Hangul Jamo": "ハングル字母",
        "Hangul Jamo Extended-A": "ハングル字母拡張A",
        "Hangul Jamo Extended-B": "ハングル字母拡張B",
        "Hangul Compatibility Jamo": "ハングル互換字母",
        "Hangul Syllables": "ハングル音節",
        "Ethiopic": "エチオピア文字",
        "Ethiopic Supplement": "エチオピア文字補助",
        "Ethiopic Extended": "エチオピア文字拡張",
        "Ethiopic Extended-A": "エチオピア文字拡張A",
        "Ethiopic Extended-B": "エチオピア文字拡張B",
        "Cherokee": "チェロキー文字",
        "Cherokee Supplement": "チェロキー文字補助",
        "Unified Canadian Aboriginal Syllabics": "統合カナダ先住民音節",
        "Unified Canadian Aboriginal Syllabics Extended": "統合カナダ先住民音節拡張",
        "Unified Canadian Aboriginal Syllabics Extended-A": "統合カナダ先住民音節拡張A",
        "Ogham": "オガム文字",
        "Runic": "ルーン文字",

        // Philippine
        "Tagalog": "タガログ文字",
        "Hanunoo": "ハヌノオ文字",
        "Buhid": "ブヒド文字",
        "Tagbanwa": "タグバンワ文字",
        "Tagbanwa (Historic)": "タグバンワ(歴史)",

        // Mongolian
        "Mongolian": "モンゴル文字",
        "Mongolian Supplement": "モンゴル文字補助",

        // Various
        "Limbu": "リンブ文字",
        "Syloti Nagri": "シロティ・ナグリ文字",
        "Phags-pa": "パスパ文字",
        "Saurashtra": "サウラーシュトラ文字",
        "Ol Chiki": "オル・チキ文字",
        "Ol Onal": "オル・オナル文字",

        // Punctuation / math / symbols
        "General Punctuation": "一般句読点",
        "Supplemental Punctuation": "補助句読点",
        "Superscripts and Subscripts": "上付き・下付き",
        "Currency Symbols": "通貨記号",
        "Letterlike Symbols": "文字様記号",
        "Number Forms": "数字に準ずるもの",
        "Arrows": "矢印",
        "Supplemental Arrows-A": "補助矢印A",
        "Supplemental Arrows-B": "補助矢印B",
        "Supplemental Arrows-C": "補助矢印C",
        "Miscellaneous Symbols and Arrows": "その他の記号と矢印",
        "Mathematical Operators": "数学記号",
        "Supplemental Mathematical Operators": "補助数学記号",
        "Miscellaneous Mathematical Symbols-A": "その他の数学記号A",
        "Miscellaneous Mathematical Symbols-B": "その他の数学記号B",
        "Miscellaneous Technical": "その他の技術記号",
        "Control Pictures": "制御文字用記号",
        "Optical Character Recognition": "光学的文字認識",
        "Enclosed Alphanumerics": "囲み英数字",
        "Enclosed Alphanumeric Supplement": "囲み英数字補助",
        "Box Drawing": "罫線素片",
        "Block Elements": "ブロック要素",
        "Geometric Shapes": "幾何学模様",
        "Geometric Shapes Extended": "幾何学模様拡張",
        "Miscellaneous Symbols": "その他の記号",
        "Miscellaneous Symbols and Pictographs": "その他の記号と絵文字",
        "Dingbats": "装飾記号",
        "Ornamental Dingbats": "装飾的な絵文字",
        "Braille Patterns": "点字図形",
        "Alphabetic Presentation Forms": "アルファベット表示形",
        "Specials": "特殊用途文字",

        // CJK
        "CJK Radicals Supplement": "CJK部首補助",
        "Kangxi Radicals": "康熙部首",
        "Ideographic Description Characters": "漢字構造記述文字",
        "Ideographic Symbols and Punctuation": "漢字記号と句読点",
        "CJK Symbols and Punctuation": "CJK記号と句読点",
        "Hiragana": "ひらがな",
        "Katakana": "カタカナ",
        "Katakana Phonetic Extensions": "片仮名拡張",
        "Bopomofo": "注音字母",
        "Bopomofo Extended": "注音字母拡張",
        "Kanbun": "漢文",
        "CJK Strokes": "CJK筆画",
        "Enclosed CJK Letters and Months": "囲みCJK文字・月",
        "CJK Compatibility": "CJK互換用文字",
        "CJK Compatibility Ideographs": "CJK互換漢字",
        "CJK Compatibility Ideographs Supplement": "CJK互換漢字補助",
        "CJK Compatibility Forms": "CJK互換形",
        "CJK Unified Ideographs": "CJK統合漢字",
        "CJK Unified Ideographs Extension A": "CJK統合漢字拡張A",
        "CJK Unified Ideographs Extension B": "CJK統合漢字拡張B",
        "CJK Unified Ideographs Extension C": "CJK統合漢字拡張C",
        "CJK Unified Ideographs Extension D": "CJK統合漢字拡張D",
        "CJK Unified Ideographs Extension E": "CJK統合漢字拡張E",
        "CJK Unified Ideographs Extension F": "CJK統合漢字拡張F",
        "CJK Unified Ideographs Extension G": "CJK統合漢字拡張G",
        "CJK Unified Ideographs Extension H": "CJK統合漢字拡張H",
        "CJK Unified Ideographs Extension I": "CJK統合漢字拡張I",
        "CJK Unified Ideographs Extension J": "CJK統合漢字拡張J",
        "Small Form Variants": "小字形",
        "Halfwidth and Fullwidth Forms": "半角・全角形",
        "Vertical Forms": "縦書き形",
        "Kana Supplement": "かな補助",
        "Kana Extended-A": "かな拡張A",
        "Kana Extended-B": "かな拡張B",
        "Small Kana Extension": "小書きかな拡張",
        "Yi Syllables": "イ文字",
        "Yi Radicals": "イ部首",
        "Lisu": "リス文字",
        "Lisu Supplement": "リス文字補助",
        "Vai": "ヴァイ文字",
        "Miao": "ミャオ文字",
        "Nushu": "女書",
        "Tangut": "西夏文字",
        "Tangut Components": "西夏文字構成要素",
        "Tangut Supplement": "西夏文字補助",
        "Khitan Small Script": "契丹小字",

        // Surrogates / Private use
        "High Surrogates": "上位サロゲート",
        "High Private Use Surrogates": "上位私用サロゲート",
        "Low Surrogates": "下位サロゲート",
        "Private Use Area": "私用領域",
        "Supplementary Private Use Area-A": "補助私用領域A",
        "Supplementary Private Use Area-B": "補助私用領域B",

        // Variation selectors / tags
        "Variation Selectors": "字形選択子",
        "Variation Selectors Supplement": "字形選択子補助",
        "Tags": "タグ",

        // SMP (suppl. multilingual plane)
        "Linear B Syllabary": "線文字B音節",
        "Linear B Ideograms": "線文字B表意文字",
        "Aegean Numbers": "エーゲ数字",
        "Ancient Greek Numbers": "古代ギリシャ数字",
        "Ancient Symbols": "古代記号",
        "Phaistos Disc": "ファイストスの円盤文字",
        "Lycian": "リキア文字",
        "Carian": "カリア文字",
        "Old Italic": "古代イタリア文字",
        "Gothic": "ゴート文字",
        "Old Permic": "古代ペルム文字",
        "Ugaritic": "ウガリト文字",
        "Old Persian": "古代ペルシャ文字",
        "Deseret": "デザレット文字",
        "Shavian": "シェイヴィアン文字",
        "Osmanya": "オスマニア文字",
        "Osage": "オーセージ文字",
        "Elbasan": "エルバサン文字",
        "Caucasian Albanian": "カフカース・アルバニア文字",
        "Vithkuqi": "ヴィトクチ文字",
        "Todhri": "トドリ文字",
        "Linear A": "線文字A",
        "Latin Extended-H": "ラテン文字拡張H",

        "Cypriot Syllabary": "キプロス音節",
        "Imperial Aramaic": "帝国アラム文字",
        "Palmyrene": "パルミラ文字",
        "Nabataean": "ナバテア文字",
        "Hatran": "ハトラ文字",
        "Phoenician": "フェニキア文字",
        "Lydian": "リディア文字",
        "Meroitic Hieroglyphs": "メロエ聖刻文字",
        "Meroitic Cursive": "メロエ草書",
        "Kharoshthi": "カローシュティー文字",
        "Old South Arabian": "古代南アラビア文字",
        "Old North Arabian": "古代北アラビア文字",
        "Manichaean": "マニ文字",
        "Avestan": "アヴェスタ文字",
        "Inscriptional Parthian": "銘文パルティア文字",
        "Inscriptional Pahlavi": "銘文パフラヴィー文字",
        "Psalter Pahlavi": "詩編パフラヴィー文字",
        "Old Turkic": "古代テュルク文字",
        "Old Hungarian": "古代ハンガリー文字",
        "Hanifi Rohingya": "ハニーフィ・ロヒンギャ文字",
        "Garay": "ガライ文字",
        "Rumi Numeral Symbols": "ルミ数字記号",
        "Yezidi": "ヤズィーディー文字",
        "Old Sogdian": "古代ソグド文字",
        "Sogdian": "ソグド文字",
        "Old Uyghur": "古代ウイグル文字",
        "Chorasmian": "ホラズム文字",
        "Elymaic": "エリマイ文字",
        "Brahmi": "ブラーフミー文字",
        "Kaithi": "カイティー文字",
        "Sora Sompeng": "ソラソンペン文字",
        "Chakma": "チャクマ文字",
        "Mahajani": "マハージャニー文字",
        "Sharada": "シャーラダー文字",
        "Sinhala Archaic Numbers (Supplement)": "シンハラ古数字補助",
        "Khojki": "ホジャ文字",
        "Multani": "ムルターニー文字",
        "Khudawadi": "フダーワディー文字",
        "Grantha": "グランタ文字",
        "Newa": "ネワ文字",
        "Tirhuta": "ティルフタ文字",
        "Siddham": "悉曇文字",
        "Modi": "モーディー文字",
        "Mongolian Supplement (Historic)": "モンゴル文字補助(歴史)",
        "Takri": "タークリー文字",
        "Ahom": "アーホム文字",
        "Dogra": "ドーグラー文字",
        "Warang Citi": "ワラング・クシティ文字",
        "Dives Akuru": "ディヴェヒ・アクル文字",
        "Nandinagari": "ナンディナーガリー文字",
        "Zanabazar Square": "ザナバザル方形文字",
        "Soyombo": "ソヨンボ文字",
        "Pau Cin Hau": "パウ・チン・ハウ文字",
        "Devanagari Extended-B": "デーヴァナーガリー文字拡張B",
        "Bhaiksuki": "バイクシュキー文字",
        "Marchen": "マルチェン文字",
        "Masaram Gondi": "マサラム・ゴーンディー文字",
        "Gunjala Gondi": "グンジャラ・ゴーンディー文字",
        "Makasar": "マカッサル文字",
        "Kawi": "カウィ文字",
        "Lisu Supplement (Historic)": "リス文字補助(歴史)",
        "Tangsa": "タンサ文字",
        "Tulu-Tigalari": "トゥル・ティガラリ文字",
        "Sunuwar": "スヌワル文字",
        "Beria Erfe": "ベリア・エルフェ文字",

        // Music / math / game / emoji
        "Byzantine Musical Symbols": "ビザンチン音楽記号",
        "Musical Symbols": "音楽記号",
        "Ancient Greek Musical Notation": "古代ギリシャ音楽記譜",
        "Kaktovik Numerals": "カクトヴィク数字",
        "Mayan Numerals": "マヤ数字",
        "Tai Xuan Jing Symbols": "太玄経記号",
        "Counting Rod Numerals": "算木",
        "Mathematical Alphanumeric Symbols": "数学用英数字記号",
        "Sutton SignWriting": "サットン手話表記",
        "Latin Extended-I": "ラテン文字拡張I(追加)",
        "Indic Siyaq Numbers": "インド・シヤク数字",
        "Ottoman Siyaq Numbers": "オスマン・シヤク数字",
        "Symbols for Legacy Computing": "レガシーコンピューティング用記号",
        "Symbols for Legacy Computing Supplement": "レガシーコンピューティング用記号補助",
        "Mahjong Tiles": "麻雀牌",
        "Domino Tiles": "ドミノ牌",
        "Playing Cards": "トランプ",
        "Enclosed Alphanumeric Supplement (Historic)": "囲み英数字補助(歴史)",
        "Enclosed Ideographic Supplement": "囲み表意文字補助",
        "Miscellaneous Symbols and Pictographs (Historic)": "その他の記号と絵文字(歴史)",
        "Emoticons": "顔文字",
        "Transport and Map Symbols": "交通・地図記号",
        "Alchemical Symbols": "錬金術記号",
        "Chess Symbols": "チェス記号",
        "Symbols and Pictographs Extended-A": "記号と絵文字拡張A",
        "Supplemental Symbols and Pictographs": "補助記号と絵文字",

        // Egyptian / Anatolian / Cuneiform / Hieroglyphs
        "Egyptian Hieroglyphs": "エジプト聖刻文字",
        "Egyptian Hieroglyph Format Controls": "エジプト聖刻文字書式制御",
        "Egyptian Hieroglyphs Extended-A": "エジプト聖刻文字拡張A",
        "Anatolian Hieroglyphs": "アナトリア聖刻文字",
        "Cuneiform": "楔形文字",
        "Cuneiform Numbers and Punctuation": "楔形数字・句読点",
        "Early Dynastic Cuneiform": "初期王朝時代楔形文字",
        "Cypro-Minoan": "キプロ・ミノア文字",
        "Bamum": "バムン文字",
        "Bamum Supplement": "バムン文字補助",
        "Mro": "ムロ文字",
        "Bassa Vah": "バサ・ヴァハ文字",
        "Pahawh Hmong": "パハウ・フモン文字",
        "Medefaidrin": "メデファイドリン文字",
        "Nyiakeng Puachue Hmong": "ニャケン・プアチュエ・フモン文字",
        "Adlam": "アドラム文字",
        "Wancho": "ワンチョ文字",
        "Toto": "トト文字",
        "Gurung Khema": "グルン・ケマ文字",
        "Kirat Rai": "キラト・ライ文字",
    ]
}

extension UnicodeBlock {
    /// Localized block name. Returns the Japanese translation when the user's
    /// preferred language is Japanese and a translation exists; otherwise the
    /// official English name.
    var localizedName: String {
        guard UnicodeBlock.isJapaneseLocale else { return name }
        return UnicodeBlocks.japaneseNames[name] ?? name
    }

    private static let isJapaneseLocale: Bool = {
        // Use `preferredLanguages` — `Locale.current` falls back to the app's
        // declared development region ("en") because the app has no ja.lproj
        // resources, even when the user's system preference is Japanese.
        Locale.preferredLanguages.first?.hasPrefix("ja") ?? false
    }()
}
